## Read and copy

## Dependencies to install

```bash
pip install pandas, pyarrow
```

In [205]:
import pandas as pd

coffeeData = pd.read_csv("coffee.csv")
coffeeData

coffee_new = coffeeData.copy() #is the right to create new copy of the data frame
coffee_new = coffeeData #just create
coffeeData

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

## loc and iloc

In [206]:
LocToSelectRows = coffeeData.loc[0:3] #0 - 3 rows, all cols
display(LocToSelectRows)

LocToSelectRows = coffeeData.loc[0:4,['Day','Units Sold']] #specify cols
display(LocToSelectRows)
LocToSelectRows = None

iLocGetColDataByIndex = coffeeData.iloc[3:6,[0,1,2]] # For iLoc specify col indexes
display(iLocGetColDataByIndex)
iLocGetColDataByIndex = None

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

         Day Coffee Type  Units Sold
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25

## at and iat

In [207]:
print(coffeeData.at[4,"Day"])
coffeeData.iat[4,1]

Wednesday

'Espresso'

## Random state

In [208]:
display( coffeeData.sample(3, random_state=2) )
display( coffeeData.sample(3, random_state=2) ) #only changing random state changes output
coffeeData.sample(3, random_state=2)[['Day','Units Sold']]

          Day Coffee Type  Units Sold
11   Saturday       Latte          35
4   Wednesday    Espresso          35
5   Wednesday       Latte          25

          Day Coffee Type  Units Sold
11   Saturday       Latte          35
4   Wednesday    Espresso          35
5   Wednesday       Latte          25

          Day  Units Sold
11   Saturday          35
4   Wednesday          35
5   Wednesday          25

## Head, Tail, Sample, Describe and Info

In [209]:
biosData = pd.read_csv("biosMini.csv")
biosData.shape # shows rows and cols count
biosData.size  # shows total number of values in data frame
biosData.head() # shows first 5 rows
biosData.head(3) # shows first 3 rows, default 5 overridden 

biosData.tail() # # shows last 5 rows

biosData.sample(5) # shows random 5 rows

display(biosData.info())     # data frame info, data types in it
display(biosData.describe())   # shows formatted values of count, mean, std, & percentiles

display(biosData.info)         # same as describe
display(biosData.describe)     # Same as info

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   athlete_id    5 non-null      int64
 1   name          5 non-null      str
 2   born_date     5 non-null      str
 3   born_city     5 non-null      str
 4   born_region   5 non-null      str
 5   born_country  5 non-null      str
 6   NOC           5 non-null      str
 7   height_cm     5 non-null      float64
 8   weight_kg     5 non-null      float64
 9   died_date     5 non-null      str
dtypes: float64(2), int64(1), str(7)
memory usage: 532.0 bytes

None

       athlete_id   height_cm  weight_kg
count    5.000000    5.000000   5.000000
mean     3.000000  179.000000  73.800000
std      1.581139    6.745369   5.585696
min      1.000000  168.000000  64.000000
25%      2.000000  177.000000  75.000000
50%      3.000000  183.000000  76.000000
75%      4.000000  183.000000  76.000000
max      5.000000  184.000000  78.000000

<bound method DataFrame.info of    athlete_id               name   born_date    born_city  \
0           1     Arnaud Boetsch  1969-04-01       Meulan
1           2       Jean Borotra  1984-08-13     Biarritz
2           3    Jacques Brugnon  1895-05-11  Paris VIIIe
3           4      Henri Leconte  1963-07-04      Lillers
4           5  Christophe Legoût  1973-08-06  Montbéliard

            born_region born_country     NOC  height_cm  weight_kg   died_date
0              Yvelines          FRA  France      183.0       76.0  1960-10-02
1  Pyrénées-Atlantiques          FRA  France      183.0       76.0  2004-07-17
2                 Paris          FRA  France      168.0       64.0  1978-03-20
3         Pas-de-Calais          FRA  France      184.0       78.0  1981-10-20
4                 Doubs          FRA  France      177.0       75.0  1978-09-24  >

<bound method NDFrame.describe of    athlete_id               name   born_date    born_city  \
0           1     Arnaud Boetsch  1969-04-01       Meulan
1           2       Jean Borotra  1984-08-13     Biarritz
2           3    Jacques Brugnon  1895-05-11  Paris VIIIe
3           4      Henri Leconte  1963-07-04      Lillers
4           5  Christophe Legoût  1973-08-06  Montbéliard

            born_region born_country     NOC  height_cm  weight_kg   died_date
0              Yvelines          FRA  France      183.0       76.0  1960-10-02
1  Pyrénées-Atlantiques          FRA  France      183.0       76.0  2004-07-17
2                 Paris          FRA  France      168.0       64.0  1978-03-20
3         Pas-de-Calais          FRA  France      184.0       78.0  1981-10-20
4                 Doubs          FRA  France      177.0       75.0  1978-09-24  >

In [210]:
biosData.index.tolist()

[0, 1, 2, 3, 4]

## loc, iloc, at, iat

In [211]:
biosData.loc[1:4,['name','height_cm']]  # #loc needs row(s) or rows range with or without columns list
biosData.iloc[3:6,[1,2,3,4,5,6]]   #iloc needs row(s) or rows range with or without columns INDEX list

biosData.at[1,"name"]
biosData.at[1,"born_region"]
type(biosData.iat[0,0])
biosData.iat[4,4]
biosData.loc[1]
display(biosData.iloc[3:6]) 
display(biosData.iloc[3,[biosData.columns.get_loc('name'),biosData.columns.get_loc('born_city')]]) # can be used for updating specific value

clist = range(1,4)
biosData.loc[clist] #range can be used , single array cell can also be used.

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20
4,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24

name         Henri Leconte
born_city          Lillers
Name: 3, dtype: str

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20

## **insert** new column with value, **update** value based on condition

In [212]:
coffeeData['Price'] = 4.99
coffeeData

coffeeData.loc[coffeeData['Coffee Type'] == 'Latte', 'Price'] = 6.99
coffeeData

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   6.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   6.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   6.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   6.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   6.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   6.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   6.99

## **inplace** to modify the original DataFrame rather than creating a df variable

In [213]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Sorting in-place (modifies the original DataFrame)
df.sort_values(by='B',ascending=False, inplace=True)

print(df)

   A  B
2  3  6
1  2  5
0  1  4

## **Duplicating** column and **Dropping** a column

In [214]:
#coffee_data = pd.read_csv('./warmup-data/coffee.csv')

coffeeData['new_price_1'] = coffeeData['Price']
display(coffeeData)
#coffee_data.drop('price') < will not work
#coffeeData.drop(columns=['new_price_1']) #< this will also not work
coffeeData.drop(columns=['new_price_1'], inplace=True  ) #< this will work
coffeeData

          Day Coffee Type  Units Sold  Price  new_price_1
0      Monday    Espresso          25   4.99         4.99
1      Monday       Latte          15   6.99         6.99
2     Tuesday    Espresso          30   4.99         4.99
3     Tuesday       Latte          20   6.99         6.99
4   Wednesday    Espresso          35   4.99         4.99
5   Wednesday       Latte          25   6.99         6.99
6    Thursday    Espresso          40   4.99         4.99
7    Thursday       Latte          30   6.99         6.99
8      Friday    Espresso          45   4.99         4.99
9      Friday       Latte          35   6.99         6.99
10   Saturday    Espresso          45   4.99         4.99
11   Saturday       Latte          35   6.99         6.99
12     Sunday    Espresso          45   4.99         4.99
13     Sunday       Latte          35   6.99         6.99

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   6.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   6.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   6.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   6.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   6.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   6.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   6.99

## Ressigning required columns by name to **Drop more Columns** if you less needed cols and more not needed cols

In [215]:
#if there are a lot of columns and you have to drop more than what you need, it'll be faster to just select what you need
# example:
coffee_data = coffeeData.copy()
coffee_data = coffee_data[['Day','Coffee Type','Units Sold','Price']]
coffee_data

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   6.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   6.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   6.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   6.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   6.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   6.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   6.99

## Add **Calculated** values in new Columns

In [216]:
coffee_data['revenue'] = coffee_data['Units Sold'] * coffee_data['Price']
coffee_data

          Day Coffee Type  Units Sold  Price  revenue
0      Monday    Espresso          25   4.99   124.75
1      Monday       Latte          15   6.99   104.85
2     Tuesday    Espresso          30   4.99   149.70
3     Tuesday       Latte          20   6.99   139.80
4   Wednesday    Espresso          35   4.99   174.65
5   Wednesday       Latte          25   6.99   174.75
6    Thursday    Espresso          40   4.99   199.60
7    Thursday       Latte          30   6.99   209.70
8      Friday    Espresso          45   4.99   224.55
9      Friday       Latte          35   6.99   244.65
10   Saturday    Espresso          45   4.99   224.55
11   Saturday       Latte          35   6.99   244.65
12     Sunday    Espresso          45   4.99   224.55
13     Sunday       Latte          35   6.99   244.65

## **Rename** single or multiple columns using a dictionary

In [217]:
coffee_data.rename(columns={'Price':'Coffee Price','revenue':'Coffee Revenue'}, inplace=True)
coffee_data

          Day Coffee Type  Units Sold  Coffee Price  Coffee Revenue
0      Monday    Espresso          25          4.99          124.75
1      Monday       Latte          15          6.99          104.85
2     Tuesday    Espresso          30          4.99          149.70
3     Tuesday       Latte          20          6.99          139.80
4   Wednesday    Espresso          35          4.99          174.65
5   Wednesday       Latte          25          6.99          174.75
6    Thursday    Espresso          40          4.99          199.60
7    Thursday       Latte          30          6.99          209.70
8      Friday    Espresso          45          4.99          224.55
9      Friday       Latte          35          6.99          244.65
10   Saturday    Espresso          45          4.99          224.55
11   Saturday       Latte          35          6.99          244.65
12     Sunday    Espresso          45          4.99          224.55
13     Sunday       Latte          35          6.99          244.65

## Sorting

In [218]:
biosData.sort_values("name")
biosData.sort_values("athlete_id",ascending=False)
#biosData.sort_values(["athelete_id","name"],ascending=[0,1])
coffeeData.sort_values(["Units Sold","Coffee Type"],ascending=[0,1])
biosData.sort_values(["name","NOC"],ascending=[1,1])
biosData.sort_values(["athlete_id","name"],ascending=[0,1]) # ascending=[0,1] 0 mean ascending sort false, 1 means ascending true for each column

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
1,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17
0,1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,1960-10-02

## **Reset Index** after sorting if you need the index to align with new sort order

In [219]:
biosDataResetIndex = biosData.sort_values(["athlete_id","name"],ascending=[0,1]).reset_index(drop=True) #Notice index starts with 0 and is in ascending order
biosDataResetIndex

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24
1,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
3,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17
4,1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,1960-10-02

## for loop **iterrows**

In [220]:
# for index, row in biosData.iterrows(): #what is intrapolate, itertuples
#     display(row)

# for i, r in biosData.iterrows(): #what is intrapolate, itertuples
#     display(r)

for i, r in biosData.iterrows(): #what is intrapolate, itertuples
    display(int(r['born_date'].split("-")[0]),r['name']) # ROW IS ASSIGNED TO OBJECT, so r(<col name>) will get values, will have refenrece row once per column
    display(r)
    print("\n\n")

1969

'Arnaud Boetsch'

athlete_id                   1
name            Arnaud Boetsch
born_date           1969-04-01
born_city               Meulan
born_region           Yvelines
born_country               FRA
NOC                     France
height_cm                183.0
weight_kg                 76.0
died_date           1960-10-02
Name: 0, dtype: object

1984

'Jean Borotra'

athlete_id                         2
name                    Jean Borotra
born_date                 1984-08-13
born_city                   Biarritz
born_region     Pyrénées-Atlantiques
born_country                     FRA
NOC                           France
height_cm                      183.0
weight_kg                       76.0
died_date                 2004-07-17
Name: 1, dtype: object

1895

'Jacques Brugnon'

athlete_id                    3
name            Jacques Brugnon
born_date            1895-05-11
born_city           Paris VIIIe
born_region               Paris
born_country                FRA
NOC                      France
height_cm                 168.0
weight_kg                  64.0
died_date            1978-03-20
Name: 2, dtype: object

1963

'Henri Leconte'

athlete_id                  4
name            Henri Leconte
born_date          1963-07-04
born_city             Lillers
born_region     Pas-de-Calais
born_country              FRA
NOC                    France
height_cm               184.0
weight_kg                78.0
died_date          1981-10-20
Name: 3, dtype: object

1973

'Christophe Legoût'

athlete_id                      5
name            Christophe Legoût
born_date              1973-08-06
born_city             Montbéliard
born_region                 Doubs
born_country                  FRA
NOC                        France
height_cm                   177.0
weight_kg                    75.0
died_date              1978-09-24
Name: 4, dtype: object

### Explanation:
- **`merge()`**: This is used to combine two DataFrames based on a common column. In this case, we’re merging on the `born_country` column from the `athlete_df` DataFrame and the `full_country_name` column from the `country_mapping_df` DataFrame.
- **`left_on`** and **`right_on`**: These parameters specify the columns to merge on in the left and right DataFrames, respectively. You’re matching the full country name from the athlete data (`born_country`) with the country name mapping.
- **`how='left'`**: This means that all rows from the left DataFrame (`athlete_df`) will be kept, even if there is no match in the right DataFrame (`country_mapping_df`).

## Filtering Data and Selecting Columns

In [221]:
biosData.loc[biosData["height_cm"]>175] # loc expects a boolean condition (True/False values) or the index of the rows you want to select.
                                        # example of this condition on height provides bolean based on which row is selected or skipped
                                        # unpack the logic by using an bolean list of size equal to the rows count in the bioData  
boolean_array = [True, False, True, False, True]
biosData.loc[boolean_array]
display( biosData.loc[boolean_array][['name','born_date']] ) #first approach
display( biosData.loc[boolean_array,['name','born_date']])   # corrected approach when not using conditions

biosData.loc[biosData["height_cm"]>175, ['name','born_date']]

                name   born_date
0     Arnaud Boetsch  1969-04-01
2    Jacques Brugnon  1895-05-11
4  Christophe Legoût  1973-08-06

                name   born_date
0     Arnaud Boetsch  1969-04-01
2    Jacques Brugnon  1895-05-11
4  Christophe Legoût  1973-08-06

                name   born_date
0     Arnaud Boetsch  1969-04-01
1       Jean Borotra  1984-08-13
3      Henri Leconte  1963-07-04
4  Christophe Legoût  1973-08-06

### Key Notes:
- **First example (`athlete_df.loc[boolean_array][['name', 'born_date']]`)**: The filtering happens first, and then you select the columns from the filtered result.
- **Second example (`athlete_df.loc[boolean_array]['name', 'born_date']`)**: This fails because it’s interpreting `['name', 'born_date']` as a tuple, not a list, which causes an error.
- **Best practice**: Use `loc[boolean_array, ['column1', 'column2']]` to filter rows and select specific columns in a single operation.

### Efficiency Difference:

- **`athlete_df.loc[athlete_df["height_cm"] > 175, ['name','born_date']]`** performs both row filtering and column selection in one step.
- **`athlete_df.loc[athlete_df["height_cm"] > 175][['name','born_date']]`** filters the rows first and then selects the columns, which involves an extra step.
- **Both are correct**, but the first approach is more efficient because it filters and selects in a single step.

In [222]:
bios_new = biosData.copy()

In [223]:
coffee_new = coffeeData.copy()
coffee_new['Units Sold'][3]
display(coffee_new)
coffee_new.loc[3,'Units Sold'] = 5
coffee_new

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   6.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   6.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   6.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   6.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   6.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   6.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   6.99

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   6.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte           5   6.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   6.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   6.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   6.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   6.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   6.99

## **add columns** using data in DF
- Wrong way
```python
df['first_name'] = df['name'].split(' ').[0]
```
This tries to apply split(' ') directly to the entire column, not to individual elements. The split() method is a standard Python string method that operates on individual strings, not on pandas Series or DataFrames. Thus, it raises an error because it's trying to split the entire column at once, which isn't possible.
- Correct way

In [224]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,1960-10-02,Arnaud
1,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17,Jean
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20,Henri
4,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24,Christophe

## Use **pd.datetime** to extract date components and add as column

- errors='coerce' to gracefully handle errors during conversion

In [225]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'], errors='coerce') # to gracefully handle errors automatically
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new #note if data had null values, year might show up as float ex. 1998.0 
#bios_new.info()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
0,1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,1960-10-02,Arnaud,1969-04-01,1969
1,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17,Jean,1984-08-13,1984
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20,Henri,1963-07-04,1963
4,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24,Christophe,1973-08-06,1973

## **query** in data frames

In [226]:
bios_new.query('first_name=="Jean"')
bios_new.query('first_name=="Jean" or born_country == "FRA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
0,1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,1960-10-02,Arnaud,1969-04-01,1969
1,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17,Jean,1984-08-13,1984
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20,Henri,1963-07-04,1963
4,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24,Christophe,1973-08-06,1973

In [227]:
bios_new[['name','born_year']] #select couple of required cols

                name  born_year
0     Arnaud Boetsch       1969
1       Jean Borotra       1984
2    Jacques Brugnon       1895
3      Henri Leconte       1963
4  Christophe Legoût       1973

## using **apply** with lambda funtion to perform conditional check and add corresponding value to the col
[DATA FRAME Apply Reference document](../Tutorials/DataFrames_applyLambda.md#L[5])

In [228]:
bios_new['height_category'] = bios_new['height_cm'].apply(lambda x: 'short' if x < 175 else ('average' if x < 180 else 'tall'))
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,1960-10-02,Arnaud,1969-04-01,1969,tall
1,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17,Jean,1984-08-13,1984,tall
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895,short
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20,Henri,1963-07-04,1963,tall
4,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24,Christophe,1973-08-06,1973,average

## **Chaining Methods** and its Impact
Pandas allows method chaining, which can lead to more readable code but can impact memory efficiency and performance. Avoid using inplace=True with chains as it will break the chain.

In [229]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

display(df)

# Chain methods to filter, sort, and reset index
df_filtered = df[df['A'] > 1].sort_values(by='B',ascending=False).reset_index(drop=True)

print(df_filtered)

   A  B
0  1  4
1  2  5
2  3  6

   A  B
0  3  6
1  2  5

## **merging** using columns with mapping values, without duplicate cols, all cols get added in left to right seq

In [230]:
athlete_df = biosData

# Sample mapping CSV (this should contain full country name and 3-letter country code)
country_mapping_df = pd.read_csv('country.csv')

# Sample data for country_mapping.csv
# country_mapping_df = pd.DataFrame({
#     'full_country_name': ['France', 'United States', 'Germany'],
#     'country_code': ['FRA', 'USA', 'DEU']
# })

# Merge athlete data with country mapping based on full country name
merged_df = pd.merge(athlete_df, country_mapping_df, left_on='NOC', right_on='full_country_name', how='left')
display(merged_df)
merged_df = None
country_mapping_df = None
athlete_df = None

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,full_country_name,country_code
0,1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,1960-10-02,France,FRA
1,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17,France,FRA
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,France,FRA
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20,France,FRA
4,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24,France,FRA

In [231]:
nocs = pd.read_csv('noc_regions.csv')

## **merging** with duplicate columns left conflicting col is suffixed with _x and right conflicting column is suffixed _y

In [232]:
bios_new_temp = pd.merge(bios_new, nocs, left_on="born_country",right_on="NOC", how='left')
bios_new_temp

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category,NOC_y,region,notes
0,1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,1960-10-02,Arnaud,1969-04-01,1969,tall,FRA,France,NaN
1,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17,Jean,1984-08-13,1984,tall,FRA,France,NaN
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895,short,FRA,France,NaN
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20,Henri,1963-07-04,1963,tall,FRA,France,NaN
4,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24,Christophe,1973-08-06,1973,average,FRA,France,NaN

In [233]:
biosData 
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,1960-10-02,Arnaud,1969-04-01,1969,tall
1,2,Jean Borotra,1984-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,2004-07-17,Jean,1984-08-13,1984,tall
2,3,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895,short
3,4,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,1981-10-20,Henri,1963-07-04,1963,tall
4,5,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,1978-09-24,Christophe,1973-08-06,1973,average

## filtered full depth copy
When you use .copy(), a deep copy of the data is created. This means that usa will be completely independent of FullBios

### Risks of Not Using .copy()

- Unintended Side Effects: If you modify usa, you might unintentionally modify FullBios because both variables will reference the same underlying data.
- SettingWithCopyWarning: If you perform chained assignments on the usa DataFrame without using .copy(), pandas might raise a SettingWithCopyWarning. This warning occurs because pandas can't guarantee whether you're modifying a copy or a view of the original DataFrame, which can lead to ambiguous and unpredictable results

In [234]:
FullBios = pd.read_csv('bios.csv')

usa = FullBios[FullBios['born_country']=='USA'].copy()
display(usa.shape)
gbr = FullBios[FullBios['born_country']=='GBR']
display(gbr.shape)

# results1 = pd.read_parquet('results.parquet')

# display(results1.head(2))
# display(FullBios.head(2))
# combined_df = pd.merge(results1, FullBios, on='athlete_id', how='left')
# display(combined_df.head(2))
# combined_df.shape

(9641, 10)

(5792, 10)

## **Memory** management
Changing data types from int64 to int32 or float64 to float32 can save significant memory without losing much precision.

In [235]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4.0, 5.0, 6.0]})
print(df.dtypes)
# Downcasting integers and floats to save memory
df['A'] = pd.to_numeric(df['A'], downcast='integer')
df['B'] = pd.to_numeric(df['B'], downcast='float')

print(df.dtypes)
df

A      int64
B    float64
dtype: object
A       int8
B    float32
dtype: object

   A    B
0  1  4.0
1  2  5.0
2  3  6.0